routes/web.php
Route::get('adminleaves/{id}/accept','AdminLeaveController@update_email')->name('adminleaves.update_email');
Route::get('adminleaves/{id}/accept2','AdminLeaveController@approve_email')->name('adminleaves.approve_email');
Route::get('adminleaves/{id}/reject','AdminLeaveController@reject_email')->name('adminleaves.reject_email');
// Route::get('/admin', 'AdminController@index');
// Route::get('/employee', 'EmployeeController@index');

Route::group( ['middleware' => ['auth']], function() {

    Route::get('/dashboard', 'DashboardController@view')->name('dashboard');
    Route::get('/dashboard/adminleaves/list/{type}','DashboardController@leavelist');
    Route::get('/dashboard/adminclaims/list/{type}','DashboardController@claimlist');
    Route::get('/dashboard/employees/list','DashboardController@probationlist');
    Route::get('/dashboard/notices/list','DashboardController@noticelist');

    Route::get('adminlieus/list','AdminLieuController@list');
    Route::get('adminlieus/list/{type}','AdminLieuController@list');
    Route::resource('adminlieus','AdminLieuController');

    Route::get('lieus/list','LieuController@list');
    Route::resource('lieus','LieuController');

    Route::get('adminleaves/list','AdminLeaveController@list');
    Route::get('adminleaves/list/{type}','AdminLeaveController@list');

    Route::resource('adminleaves','AdminLeaveController');
    //calendar
    Route::get('events', 'EventController@index')->name('events.index');
    Route::get('events/list', 'EventController@eventlist');
    Route::delete('events/list/{id}', 'EventController@delete')->name('events.destroy');
    Route::post('events', 'EventController@addEvent')->name('events.add');
    // event for employee
    Route::get('empevents', 'EventController@employeeindex');


    Route::get('profile', 'ProfileController@my')->name('profile.my');
    Route::get('profile/documents', 'ProfileController@documents')->name('profile.documents');
    Route::post('profile/image', 'ProfileController@upload_image')->name('profile.image.upload');

    Route::get('employees/list', 'EmployeeController@list');
    Route::post('employees/image/{employee}', 'EmployeeController@upload_image')->name('employees.image.upload');
    Route::put('employees/account/update/{employee}', 'EmployeeController@account_update')->name('employees.account.update');
    Route::put('employees/info/update/{employee}', 'EmployeeController@employee_update')->name('employees.info.update');
    Route::put('employees/leave/update/{employee}', 'EmployeeController@leave_update')->name('employees.leave.update');
    Route::resource('employees', 'EmployeeController');

    Route::resource('employees.contacts', 'EmployeeContactController');
    Route::resource('employees.histories', 'EmployeeHistoryController');
    Route::resource('employees.educations', 'EmployeeEducationController');
    Route::resource('employees.certificates', 'EmployeeCertificateController');
    Route::resource('employees.medicals', 'EmployeeMedicalController');
    // Route::get('employee/assets/list', 'EmployeeAssetController@list');
    Route::resource('employees.assets', 'EmployeeAssetController');
    Route::resource('employees.documents', 'EmployeeDocumentController');

    Route::post('employees/save/approval/{employee}', 'ApprovalController@approve_update')->name('approve.save');

    Route::get('organisations/list', 'OrganisationController@list');
    Route::resource('organisations','OrganisationController');

    Route::get('departments/list', 'DepartmentController@list');
    Route::resource('departments','DepartmentController');

    Route::get('designations/list', 'DesignationController@list');
    Route::get('designations/department/{id}', 'DesignationController@list_based_department');
    Route::resource('designations','DesignationController');

    Route::get('hierarchies/list', 'HierarchyController@list');
    Route::resource('hierarchies','HierarchyController');

    // Route::resource('leaves','LeaveController');
    Route::resource('adminroles','AdminRoleController');

    Route::get('roles/list', 'RoleController@list');
    Route::resource('roles','RoleController');

    Route::resource('holiday','AdminHolidayController');

    // Assets
    Route::get('assets/list','AssetController@list');
    Route::get('assets/brand/{id}', 'AssetController@list_based_asset');
    Route::resource('assets','AssetController');

    // Asset Type
    Route::get('types/list','AssetTypeController@list');
    Route::resource('types','AssetTypeController');

    // Asset Brand
    Route::get('brands/list','AssetBrandController@list');
    Route::get('brands/type/{id}', 'AssetBrandController@list_based_type');
    Route::resource('brands','AssetBrandController');

    // Assign Asset
    Route::get('assigns/list','AssignController@list');
    Route::get('assigns/employee/{id}', 'AssignController@list_based_employee');
    // Route::get('assigns/type/{id}', 'AssignController@list_based_type');
    // Route::get('assigns/brand/{id}', 'AssignController@list_based_brand');
    Route::resource('assigns','AssignController');

    // Notices

    Route::get('notices/list','NoticeController@list');
    Route::get('notices/employee/{id}', 'NoticeController@list_based_employee');
    Route::resource('notices','NoticeController');

    //web setting
    Route::get('documents/list','AdminSettingsController@list_document')->name('settings.document.list');
    Route::post('settings/store_leave','AdminSettingsController@store_leave')->name('settings.store_leave');
    Route::post('settings/store_system','AdminSettingsController@store_system')->name('settings.store_system');
    Route::post('settings/store_document','AdminSettingsController@store_document')->name('settings.store_document');
    Route::delete('settings/delete_document/{id}', 'AdminSettingsController@delete_document')->name('default_documents.destroy');
    Route::resource('settings','AdminSettingsController');

    // Payslip
    Route::get('payslips/list','PayrollCategoryController@list');
    Route::resource('payslips','PayrollCategoryController');

    // Salaries
    Route::get('salaries/list','SalaryController@list');
    Route::get('salaries/employee/{id}', 'SalaryController@list_based_employee');
    Route::get('salaries/salary/{id}','SalaryController@salary')->name('salaries.salary');
    Route::post('salaries/set','SalaryController@set')->name('salaries.set');
    Route::get('salaries/increment/{id}','SalaryController@increment')->name('salaries.increment');
    Route::resource('salaries','SalaryController');
    // employee payroll
    Route::get('empgenerates','EmployeePayrollController@index');
    Route::get('empgenerates/{years}/{month}','EmployeePayrollController@index2');
    Route::get('empgenerates/{years}/{month}/list','EmployeePayrollController@list');
    Route::get('empgenerates/{years}/{month}/{id}/print','EmployeePayrollController@print')->name('empgenerates.print');

    // Generate
    Route::get('generates','PayrollController@index');
    Route::get('generates/{years}/{month}','PayrollController@index2');
    Route::get('generates/{years}/{month}/list','PayrollController@list');
    Route::get('generates/{years}/{month}/genlist','PayrollController@genlist');

    Route::get('generates/{years}/{month}/{id}','PayrollController@generate')->name('generates.generate');

    // Route::post('generates/{years}/{month}/store')->name('generates.store');
    Route::get('generates/{years}/{month}/addition','PayrollController@addition')->name('generates.additem');
    Route::post('generates/{years}/{month}/store_add','PayrollController@store_add')->name('generates.store_add');
    Route::get('generates/{years}/{month}/deduction','PayrollController@deduction');
    Route::post('generates/{years}/{month}/store_deduct','PayrollController@store_deduct')->name('generates.store_deduct');
    Route::post('generates/{years}/{month}/store_gen','PayrollController@store_gen')->name('generates.store_gen');
    Route::get('generates/{years}/{month}/{id}/print','PayrollController@print')->name('generates.print');
    //Route::resource('generates','PayrollController');

    //
   // Route::get('generates/addition','PayrollController@addition');
   // Route::post('generates/addition/store_add','PayrollController@store_add')->name('generates.store_add');
  //  Route::get('generates/deduction','PayrollController@deduction');
   // Route::post('generates/deduction/store_deduct','PayrollController@store_deduct')->name('generates.store_deduct');
  //  Route::get('generates/{years}/{month}/list','PayrollController@list');
    // Route::get('generates/{years}/{month}/genlist','PayrollController@genlist');
    // Route::get('generates/generate/{years}/{month}/{id}/print','PayrollController@print')->name('generates.print');
   // Route::get('generates/{years}/{month}/{id}','PayrollController@generate')->name('generates.generate');
    // Route::get('generates','PayrollController@payslip');
   // Route::delete('generates/generate/{id}/{category_id}/delete','PayrollController@destroy')->name('generates.destroy');


    // Employee Resource
    // cuti punya resorce
    Route::post('employees/leaves/emergencies', 'EmergencyController@store')->name('leaves.store.emergency');
    Route::resource('emergencies','EmergencyController');
    Route::post('employees/leaves/annuals','EmployeeLeaveController@store_annual')->name('leaves.store.annuals');
    Route::resource('annuals','EmployeeLeaveController');
    Route::post('employees/leaves/compassionates','CompassionateController@store')->name('leaves.store.compassionates');
    Route::resource('compassionates','CompassionateController');
    Route::post('employees/leaves/medics','MedicalController@store')->name('leaves.store.medical');
    Route::resource('medics','MedicalController');
    Route::post('employees/leaves/marriages','MarriageController@store')->name('leaves.store.marriage');

app/Http/Controllers/HierarchyController.php
<?php

namespace App\Http\Controllers;

use App\Hierarchy;
use Illuminate\Http\Request;
use DataTables;

class HierarchyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    public function list(){
        return Datatables::eloquent(Hierarchy::query())
        ->addColumn('action', function($model){
            $url = 'hierarchies';
            $show_hide = true;
            $modal_view_id = 'modal_hierarchies_show';
            $modal_edit_id = 'modal_hierarchies_edit';
            $delete_datatable_id_name_refresh = 'dept_table';
            return view('shared._table_action', compact('model', 'url', 'show_hide','modal_view_id', 'modal_edit_id'))->render();
        })
        ->addIndexColumn()
        ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admins.organisations.hierarchies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $hierarchies = Hierarchy::create($request->only('hierarchy_name','hierarchy_ranking'));
        $hierarchies->save();
        return redirect()->route('organisations.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Hierarchy  $hierarchy
     * @return \Illuminate\Http\Response
     */
    public function show(Hierarchy $hierarchy)
    {
        $hierarchies = Hierarchy::where('id', $id)->first();
        return View ('admins.organisations.hierarchies.show',compact('hierarchies'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Hierarchy  $hierarchy
     * @return \Illuminate\Http\Response
     */
    public function edit(Hierarchy $hierarchy)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Hierarchy  $hierarchy
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Hierarchy $hierarchy)
    {
        $hierarchy->update($request->all());
        return response()->json($hierarchy, 201);//
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Hierarchy  $hierarchy
     * @return \Illuminate\Http\Response
     */
    public function destroy(Hierarchy $hierarchy)
    {
        $hierarchy->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/OrganisationController.php
<?php

namespace App\Http\Controllers;

use App\Organisation;
use App\Department;
use App\Designation;
use App\Hierarchy;
use Illuminate\Http\Request;
use DataTables;

class OrganisationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $designations = Designation::all();
        $hierarchies = Hierarchy::all();
        $departments = Department::all();

        return view('admins.organisations.index',compact('designations','hierarchies', 'departments'));
    }

    public function list(){
        return Datatables::eloquent(Organisation::query())
        ->addColumn('action', function($model){
            $url = 'organisations';
            $show_hide = true;
            $modal_view_id = 'modal_organisations_show';
            $modal_edit_id = 'modal_organisations_edit';
            if($model->getMedia('logo')->first()){
                $modal_data_customs = array('logo' => $model->getMedia('logo')->first()->getUrl());
            }
            return view('shared._table_action', compact('model', 'url', 'show_hide', 'modal_view_id', 'modal_edit_id', 'modal_data_customs'))->render();
        })
        ->addIndexColumn()
        ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admins.organisations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'company_name' => 'bail|required',
            'reg_num' => 'bail|required',
            'address1' => 'bail|required',
            'address2' => 'bail|required',
            'state' => 'bail|required',
            'country' => 'bail|required',
            'website' => 'bail|required',
            'fb' => 'bail|required',
            'linkedin' => 'bail|required',
            'other' => 'bail|required',
            'number' => 'bail|required',
            'fax' => 'bail|required',
            'business' => 'bail|required',
            'tax' => 'bail|required',

        ]);

        // $organisation = Organisation::create($request->only('company_name','reg_num'));

        $organisation = new Organisation;
        $organisation->company_name = $request->company_name;
        $organisation->reg_num = $request->reg_num;
        $organisation->address1 = $request->address1;
        $organisation->address2 = $request->address2;
        $organisation->city = $request->city;
        $organisation->state = $request->state;
        $organisation->country = $request->country;
        $organisation->number = $request->number;
        $organisation->fax = $request->fax;
        $organisation->website = $request->website;
        $organisation->fb = $request->fb;
        $organisation->linkedin = $request->linkedin;
        $organisation->other = $request->other;
        $organisation->business = $request->business;
        $organisation->natureoforg = $request->status;
        $organisation->tax = $request->tax;

        $organisation->save();

        if ($request->hasFile('file')) {
            $organisation->addMediaFromRequest('file')->toMediaCollection('logo');
        }

        return response()->json($organisation, 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $designations = Designation::find($id);
        // $departments = Department::find($id);
        // $organisations = Organisation::find($id);
        // return view('admins.organisations.show',compact('organisations','designations','departments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $organisation = Organisation::find($id);
        $organisation->update($request->all());

        if ($request->hasFile('file')) {
            $organisation->clearMediaCollection('logo');
            $organisation->addMediaFromRequest('file')->toMediaCollection('logo');
        }

        return response()->json($organisation, 201);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $organisation = Organisation::find($id);
        $organisation->delete();
        return redirect()->back();
    }
}

resources/views/admins/organisations/hierarchies/create.blade.php
<div id="add-hierarchy" class="modal fade in" tabindex="-1" role="dialog" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                <h1>Add New Hierarchy</h1>
                {!! Form::open(['url' => 'hierarchies', 'id' => 'hierarchy_create']) !!}

                    <div class="form-group row">
                        <div class="col-md-9">
                        {{Form::text('hierarchy_name', null , ['required','class' => 'form-control','placeholder' => 'Hierarchy Name'])}}
                        {{-- <input type="text" class="form-control" placeholder="Hierarchy Name"> --}}
                    </div>
                    <div class="col-md-3">
                            {!! Form::select('hierarchy_ranking', ['10' => '10', '9' => '9', '8' => '8', '7' => '7', '6' => '6', '5' => '5', '4' => '4', '3' => '3', '2' => '2', '1' => '1'], null,
                            ['class' => 'form-control', 'placeholder' => 'Select Rank'] ); !!}
                    </div>
                </div>
                {{Form::submit('Add Hierarchy',['class' =>'btn btn-rounded btn-info text-uppercase'])}}
                <button type="button" class="text-uppercase btn btn-danger btn-rounded waves-effect" data-dismiss="modal">Close</button>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>


@section('js')
    @parent
    <script>

    $('#add-hierarchy').on('hidden.bs.modal', function(e) {
        $(this).find('#hierarchy_create')[0].reset();
    });

    $( "#hierarchy_create" ).on( "submit", function( event ) {
        event.preventDefault();
        swal({
            title: "Submit Hierarchy",
            text: "Are you sure you want to submit this hierarchy?",
            type: "info",
            showCancelButton: true,
            showLoaderOnConfirm: true,
            preConfirm: function() {
                var form = document.getElementById('hierarchy_create');
                var formData = new FormData(form);
                $.ajax({
                    type: "POST",
                    url: '{{ route('hierarchies.store') }}',
                    data: formData,
                    cache:false,
                    contentType: false,
                    processData: false,
                    success: function(msg) {
                        return msg;
                    }
                });
            }
        }).then((result) => {
            $('#add-hierarchy').modal('toggle');
            if(result.value){
                $('#hierarchy_table').DataTable().ajax.reload();
                swal('New Hierarchy Added!', '--', 'success');
            }
        });
    });
    </script>
@endsection

resources/views/admins/organisations/hierarchies/edit.blade.php
<div id="modal_hierarchies_edit" class="modal fade in" tabindex="-1" role="dialog" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                <h1>Add New Hierarchy</h1>
                {!! Form::open(['url' => 'hierarchies', 'id' => 'hierarchy_edit']) !!}
                    {{ Form::hidden('hierarchy_id', null , ['id' => 'hierarchy_id']) }}
                    <input type="hidden" name="_method" value="PUT">


                    <div class="form-group row">
                        <div class="col-md-9">
                        {{Form::text('hierarchy_name', null , ['required','class' => 'form-control','placeholder' => 'Hierarchy Name', 'id' => 'hierarchy_name'])}}
                    </div>
                    <div class="col-md-3">
                        {!! Form::select('hierarchy_ranking',
                        ['10' => '10', '9' => '9', '8' => '8', '7' => '7', '6' => '6', '5' => '5', '4' => '4', '3' => '3', '2' => '2', '1' => '1'], null,
                        ['class' => 'form-control', 'placeholder' => 'Select Rank', 'id' => 'hierarchy_ranking'] ); !!}
                    </div>
                </div>
                {{Form::submit('Save Hierarchy',['class' =>'btn btn-rounded btn-info text-uppercase'])}}
                <button type="button" class="text-uppercase btn btn-danger btn-rounded waves-effect" data-dismiss="modal">Close</button>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@section('js')
    @parent
    <script>

    $( "#hierarchy_edit" ).on( "submit", function( event ) {
        event.preventDefault();
        swal({
            title: "Update Hierarchy",
            text: "Are you sure you want to update this hierarchy?",
            type: "info",
            showCancelButton: true,
            showLoaderOnConfirm: true,
            preConfirm: function() {
                var form = document.getElementById('hierarchy_edit');
                var formData = new FormData(form);
                $.ajax({
                    type: "POST",
                    url: '/hierarchies/'+form.hierarchy_id.value,
                    data: formData,
                    cache:false,
                    contentType: false,
                    processData: false,
                    success: function(msg) {
                        return msg;
                    }
                });
            }
        }).then((result) => {
            $('#modal_hierarchies_edit').modal('toggle');
            if(result.value){
                $('#hierarchy_table').DataTable().ajax.reload();
                swal('Hierarchy Updated!', '--', 'success');
            }
        });
    });
    </script>
@endsection

resources/views/admins/organisations/hierarchies/show.blade.php
<div id="show-hierarchy{{$hierarchy->id}}" class="modal fade in" tabindex="-1" role="dialog" >
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                    <h1>Hierarchy Details</h1>

                    {!! Form::open(['url' => 'hierarchies']) !!}
                <div class="  form-group ">
                        {!! Form::label('Hierarchy Name') !!}
                    {{Form::text('hierarchies',$hierarchy->hierarchy_name,array('class' => 'form-control')) }}
                </div>
                <div class="  form-group ">
                        {!! Form::label('Rank') !!}
                        {{Form::text('hierarchies',$hierarchy->hierarchy_ranking,array('class' => 'form-control')) }}
                    </div>
                {{-- {{Form::submit('Close',['class' => 'btn btn-lg btn-info pull-right'])}} --}}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>