routes/web.php
    Route::resource('employees.contacts', 'EmployeeContactController');
    Route::resource('employees.histories', 'EmployeeHistoryController');
    Route::resource('employees.educations', 'EmployeeEducationController');
    Route::resource('employees.certificates', 'EmployeeCertificateController');
    Route::resource('employees.medicals', 'EmployeeMedicalController');
    // Route::get('employee/assets/list', 'EmployeeAssetController@list');
    Route::resource('employees.assets', 'EmployeeAssetController');
    Route::resource('employees.documents', 'EmployeeDocumentController');

    Route::post('employees/save/approval/{employee}', 'ApprovalController@approve_update')->name('approve.save');

    Route::get('organisations/list', 'OrganisationController@list');
    Route::resource('organisations','OrganisationController');

    Route::get('departments/list', 'DepartmentController@list');
    Route::resource('departments','DepartmentController');

    Route::get('designations/list', 'DesignationController@list');
    Route::get('designations/department/{id}', 'DesignationController@list_based_department');
    Route::resource('designations','DesignationController');

    Route::get('hierarchies/list', 'HierarchyController@list');
    Route::resource('hierarchies','HierarchyController');

    // Route::resource('leaves','LeaveController');
    Route::resource('adminroles','AdminRoleController');

    Route::get('roles/list', 'RoleController@list');
    Route::resource('roles','RoleController');

    Route::resource('holiday','AdminHolidayController');

    // Assets
    Route::get('assets/list','AssetController@list');
    Route::get('assets/brand/{id}', 'AssetController@list_based_asset');
    Route::resource('assets','AssetController');

    // Asset Type
    Route::get('types/list','AssetTypeController@list');
    Route::resource('types','AssetTypeController');

    // Asset Brand
    Route::get('brands/list','AssetBrandController@list');
    Route::get('brands/type/{id}', 'AssetBrandController@list_based_type');
    Route::resource('brands','AssetBrandController');

    // Assign Asset
    Route::get('assigns/list','AssignController@list');
    Route::get('assigns/employee/{id}', 'AssignController@list_based_employee');
    // Route::get('assigns/type/{id}', 'AssignController@list_based_type');
    // Route::get('assigns/brand/{id}', 'AssignController@list_based_brand');
    Route::resource('assigns','AssignController');

    // Notices

    Route::get('notices/list','NoticeController@list');
    Route::get('notices/employee/{id}', 'NoticeController@list_based_employee');
    Route::resource('notices','NoticeController');

    //web setting
    Route::get('documents/list','AdminSettingsController@list_document')->name('settings.document.list');
    Route::post('settings/store_leave','AdminSettingsController@store_leave')->name('settings.store_leave');
    Route::post('settings/store_system','AdminSettingsController@store_system')->name('settings.store_system');
    Route::post('settings/store_document','AdminSettingsController@store_document')->name('settings.store_document');
    Route::delete('settings/delete_document/{id}', 'AdminSettingsController@delete_document')->name('default_documents.destroy');
    Route::resource('settings','AdminSettingsController');

    // Payslip
    Route::get('payslips/list','PayrollCategoryController@list');
    Route::resource('payslips','PayrollCategoryController');

    // Salaries
    Route::get('salaries/list','SalaryController@list');
    Route::get('salaries/employee/{id}', 'SalaryController@list_based_employee');
    Route::get('salaries/salary/{id}','SalaryController@salary')->name('salaries.salary');
    Route::post('salaries/set','SalaryController@set')->name('salaries.set');
    Route::get('salaries/increment/{id}','SalaryController@increment')->name('salaries.increment');
    Route::resource('salaries','SalaryController');
    // employee payroll
    Route::get('empgenerates','EmployeePayrollController@index');
    Route::get('empgenerates/{years}/{month}','EmployeePayrollController@index2');
    Route::get('empgenerates/{years}/{month}/list','EmployeePayrollController@list');
    Route::get('empgenerates/{years}/{month}/{id}/print','EmployeePayrollController@print')->name('empgenerates.print');

    // Generate
    Route::get('generates','PayrollController@index');
    Route::get('generates/{years}/{month}','PayrollController@index2');
    Route::get('generates/{years}/{month}/list','PayrollController@list');
    Route::get('generates/{years}/{month}/genlist','PayrollController@genlist');

    Route::get('generates/{years}/{month}/{id}','PayrollController@generate')->name('generates.generate');

    // Route::post('generates/{years}/{month}/store')->name('generates.store');
    Route::get('generates/{years}/{month}/addition','PayrollController@addition')->name('generates.additem');
    Route::post('generates/{years}/{month}/store_add','PayrollController@store_add')->name('generates.store_add');
    Route::get('generates/{years}/{month}/deduction','PayrollController@deduction');
    Route::post('generates/{years}/{month}/store_deduct','PayrollController@store_deduct')->name('generates.store_deduct');
    Route::post('generates/{years}/{month}/store_gen','PayrollController@store_gen')->name('generates.store_gen');
    Route::get('generates/{years}/{month}/{id}/print','PayrollController@print')->name('generates.print');
    //Route::resource('generates','PayrollController');

    //
   // Route::get('generates/addition','PayrollController@addition');
   // Route::post('generates/addition/store_add','PayrollController@store_add')->name('generates.store_add');
  //  Route::get('generates/deduction','PayrollController@deduction');
   // Route::post('generates/deduction/store_deduct','PayrollController@store_deduct')->name('generates.store_deduct');
  //  Route::get('generates/{years}/{month}/list','PayrollController@list');
    // Route::get('generates/{years}/{month}/genlist','PayrollController@genlist');
    // Route::get('generates/generate/{years}/{month}/{id}/print','PayrollController@print')->name('generates.print');
   // Route::get('generates/{years}/{month}/{id}','PayrollController@generate')->name('generates.generate');
    // Route::get('generates','PayrollController@payslip');
   // Route::delete('generates/generate/{id}/{category_id}/delete','PayrollController@destroy')->name('generates.destroy');


    // Employee Resource
    // cuti punya resorce
    Route::post('employees/leaves/emergencies', 'EmergencyController@store')->name('leaves.store.emergency');
    Route::resource('emergencies','EmergencyController');
    Route::post('employees/leaves/annuals','EmployeeLeaveController@store_annual')->name('leaves.store.annuals');
    Route::resource('annuals','EmployeeLeaveController');
    Route::post('employees/leaves/compassionates','CompassionateController@store')->name('leaves.store.compassionates');
    Route::resource('compassionates','CompassionateController');
    Route::post('employees/leaves/medics','MedicalController@store')->name('leaves.store.medical');
    Route::resource('medics','MedicalController');
    Route::post('employees/leaves/marriages','MarriageController@store')->name('leaves.store.marriage');
    Route::resource('marriages','MarriageController');
    Route::post('employees/leaves/maternity','MaternityController@store')->name('leaves.store.maternity');
    Route::resource('maternity','MaternityController');
    Route::post('employees/leaves/paternity','PaternityController@store')->name('leaves.store.paternity');
    Route::resource('paternity','PaternityController');

    Route::get('leaves/list','EmployeeLeaveController@list');
    Route::get('leaves/{id}','EmployeeLeaveController@list');
    // Route::put('leaves/{id}/update','EmployeeLeaveController@update');
    Route::resource('leaves','EmployeeLeaveController');



    // Route::name('admin.')->prefix('admin')->group(function () {
    //     Route::get('lieus/{id}/status/{status}', 'Admin\LieuController@liew_update_status');
    //     Route::resource('lieus','Admin\LieuController');
    // });

    // Claims
    Route::get('claims/create/draft', 'ClaimController@create_draft')->name('claims.monthly.create');
    Route::get('claims/list', 'ClaimController@list');
    Route::get('claims/country_list', 'ClaimController@country_list');
    Route::get('claims/list_request', 'ClaimController@list_request');
    Route::get('claims/month/{id}','ClaimController@show')->name('claims.monthly.show');
    Route::put('claims/submit/{id}', 'ClaimController@submit_advance')->name('claims.submit.advance');
    Route::resource('claims','ClaimController');

    // Claim Advances
    Route::get('claimadvances/create/draft', 'ClaimController@create_advance_draft')->name('claims.advance.create');
    Route::get('claimadvances/{id}','ClaimController@show_advance')->name('claimadvances.show');
    Route::get('claimadvances/detail/{id}','ClaimController@show_advance_detail')->name('claimadvances_detail.show');
    Route::put('claimadvances/update/{id}','ClaimController@update_advance')->name('claimadvances.update');
    Route::delete('claimadvances/delete/{id}','ClaimController@destroy_advance')->name('claimadvances.destroy');
    // Route::resource('claimadvances','AdvancesClaimController');

    // Admin Claims
    Route::get('adminclaims/list', 'AdminClaimController@list');
    Route::get('adminclaims/list/{type}', 'AdminClaimController@list');
    Route::get('adminclaims/list_request/{type}', 'AdminClaimController@list_request');
    Route::get('adminclaims/list_advance/{type}', 'AdminClaimController@list_advance');
    Route::get('adminclaims_request/{id}', 'AdminClaimController@show_request')->name('adminclaims_request.show');
    Route::put('adminclaims/update_admin/{id}', 'AdminClaimController@update_admin')->name('claim.update.admin');

resources/views/payslips/create.blade.php
<div class="modal fade" id="add-payroll-cat">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    {!! Form::open(['url' => 'payslips', "id" => "payroll_create",]) !!}
                    <h1>Add Payroll Category</h1>

                   <div class="form-group">
                        {!! Form::label('Payroll Category Name') !!}
                        {{Form::text('name', null , ['required','class' => 'form-control','placeholder' => 'Create Name'])}}
                    </div>

                    <div class="form-group row">
                        <div class="col-md-6">
                                {!! Form::label('Operand Select') !!}
                                <select class="form-control" name="operand_id" id="operand_id" data-parsley-required="true">
                                        @foreach ($operands as $operand)
                                            <option value="{{ $operand->id }}">{{ $operand->operand_name }}</option>
                                        @endforeach
                                </select>
                                {{-- {{Form::select('operand', ['Addition' => 'Addition', 'Deduction' => 'Deduction'], null, ['class' => 'form-control', 'placeholder' => 'Select Status'])}} --}}
                            </div>
                    </div>
               {{Form::submit('Create Category',['class' =>'btn btn-rounded btn-info text-uppercase'])}}
               <button type="button" class="text-uppercase btn btn-danger btn-rounded waves-effect" data-dismiss="modal">Close</button>
               {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    @section('js')
    @parent
    <script>

    $('#add-category').on('hidden.bs.modal', function(e) {
        $(this).find('#payroll_create')[0].reset();
    });

    $( "#payroll_create" ).on( "submit", function( event ) {
        event.preventDefault();
        swal({
            title: "Payroll Category",
            text: "Confirm to payroll category?",
            type: "info",
            showCancelButton: true,
            showLoaderOnConfirm: true,
            preConfirm: function() {
                var form = document.getElementById('payroll_create');
                var formData = new FormData(form);
                $.ajax({
                    type: "POST",
                    url: '{{ route('payslips.store') }}',
                    data: formData,
                    cache:false,
                    contentType: false,
                    processData: false,
                    success: function(msg) {
                        return msg;
                    }
                });
            }
        }).then((result) => {
            $('#add-category').modal('toggle');
            if(result.value){
                $('#payroll_table').DataTable().ajax.reload(function(json){
                    var len = json.data.length;
                    $("#payslips").empty();
                    $("#payslips").append("<option value=''>Please Select</option>");
                    for( var i = 0; i<len; i++){
                        var id = json.data[i]['id'];
                        var name = json.data[i]['title'];
                        $("#payslips").append("<option value='"+id+"'>"+name+"</option>");

                    }
                });

                //reload select designation


                swal('New Category Added!', '--', 'success');
            }
        });
    });
    </script>
    @endsection

resources/views/payslips/edit.blade.php
<div id="modal_payroll_edit" class="modal fade in" tabindex="-1" role="dialog" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                <h1>Edit Payroll Category</h1>
                    {!! Form::open(['url' => 'payslips', 'id' => 'payroll_edit']) !!}
                    {{ Form::hidden('id', null , ['id' => 'id']) }}
                    <input type="hidden" name="_method" value="PUT">
                    <div class="form-group ">
                        <p class="text-muted">PAYROLL CATEGORY NAME</p>
                        {{Form::text('name', null , ['id' => 'payroll_name_edit', 'required','class' => 'form-control','placeholder' => 'edit asset name'])}}
                    </div>
                    <div class="form-group ">
                        <p class="text-muted">PAYROLL OPERAND</p>
                        <H4><span id="modal_payroll_operand"> </span></H4>
                    </div>
                    {{Form::submit('Update Details',['class' =>'btn btn-rounded btn-info text-uppercase'])}}
                    <button type="button" class="text-uppercase btn btn-danger btn-rounded waves-effect" data-dismiss="modal">Close</button>
                    {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@section('js')
    @parent
    <script>

    $( "#payroll_edit" ).on( "submit", function( event ) {
        event.preventDefault();
        swal({
            title: "Update Category Details",
            text: "Change the details of this category?",
            type: "info",
            showCancelButton: true,
            showLoaderOnConfirm: true,
            preConfirm: function() {
                var form = document.getElementById('payroll_edit');
                var formData = new FormData(form);
                $.ajax({
                    type: "POST",
                    url: '/payslips/'+form.id.value,
                    data: formData,
                    cache:false,
                    contentType: false,
                    processData: false,
                    success: function(msg) {
                        return msg;
                    }
                });
            }
        }).then((result) => {
            $('#modal_payroll_edit').modal('toggle');
            if(result.value){
                $('#payroll_table').DataTable().ajax.reload();
                swal('Category Details Updated!', '--', 'success');
            }
        });
    });
    </script>
@endsection

resources/views/payslips/index.blade.php
@extends('layouts.default.master')

@section('content')

<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
    </svg>
</div>

<div id="page-wrapper">
        <div class="container-fluid">
            <div class="row bg-title">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Payslip</h4>
                </div>
                <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                    <ol class="breadcrumb">
                        <li><a href="dashboard-adminview.html">Dashboard</a></li>
                        <li class="active">Payslip</li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <h3 class="box-title">Payroll Categories
                           <a href="#add-payroll-cat" data-toggle="modal" class="pull-right m-t--5 btn btn-rounded btn btn-info text-uppercase">Add Payroll Category</a></h3>
                        <div class="table-responsive">
                            <table  id="payroll_table" class="">
                                <thead>
                                    <tr>
                                        <th style="width: 5%">#</th>
                                        <th>Category Name</th>
                                        <th>Operand</th>
                                        <th style="width: 20%">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!--row -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <h3 class="box-title">Salary List
                           {{-- <a href="#add-salary" data-toggle="modal" class="pull-right m-t--5 btn btn-rounded btn btn-info text-uppercase">Add Payroll Category</a> --}}
                             </h3>
                        <div class="table-responsive">
                            <table  id="salary_table" class="">
                                <thead>
                                    <tr>
                                        <th style="width: 5%">#</th>
                                        <th>Employee</th>
                                        <th>Salary</th>
                                        <th style="width: 20%">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>


                    </div>
                </div>
            </div>
            <!--row -->

            <!--modal category-->
            @include('payslips.show')
            @include('payslips.create')
            @include('payslips.edit')

             <!--modal set salary-->
            @include('payslips.salaries.set')

              {{-- <!--modal set increment-->
            @include('payslips.salaries.increment') --}}

        </div>
        <!-- /.container-fluid -->
    </div>
@endsection

@section('js')
@parent

<script>
$(function () {

    $('#payroll_table').DataTable({
        serverSide: true,
        processing: true,
        ajax: '/payslips/list',
        columns: [
            {data: 'DT_Row_Index', orderable: false, searchable: false},
            {data: 'name'},
            {data: 'operand', name: 'operand.operand_name'},
            {data: 'action', orderable: false, searchable: false}
        ]
    });

    $('#salary_table').DataTable({
        serverSide: true,
        processing: true,
        ajax: '/salaries/list',
        columns: [
            {data: 'DT_Row_Index', orderable: false, searchable: false},
            {data: 'username'},
            {data: 'salary' },
            {data: 'action', orderable: false, searchable: false}
        ]
    });

});

    $(document).off('click', '.open-modal').on("click", ".open-modal", function () {


        var data = $(this).data('modal_data');

        //if($(this).data('salary') ){ //data-employee
        //    var salary = $(this).data('salary');
        //}

        // Payroll

        $('#modal_payroll_show').on('shown.bs.modal', function(e){
            $(".modal-body #modal_payroll_name").text(data.name);
            $(".modal-body #modal_payroll_operand").val(data.operand_id)
            $(this).off('shown.bs.modal');
            console.log(name);
        });

        $('#modal_payroll_show').on('hide.bs.modal', function(e){
            $(".modal-body #modal_payroll_name").text('');
            $(".modal-body #modal_payroll_operand").text('');
            $(this).off('hide.bs.modal');
        });

        $('#modal_payroll_edit').on('shown.bs.modal', function(e){
            $(".modal-body #payroll_name_edit").val(data.name);
            $(".modal-body #modal_payroll_operand").val(data.operand_id)
            $(".modal-body #id").val(data.id);
            $(this).off('shown.bs.modal');
        });

        $('#modal_payroll_edit').on('hide.bs.modal', function(e){
            $(this).find('#payroll_edit')[0].reset();
            $(this).off('hide.bs.modal');
        });

        // Salary

        $('#modal_salary_set').on('shown.bs.modal', function(e){

            $(".modal-body #modal_salary_name").text(data.lname);

            $(".modal-body #modal_salary_username").text(data.fname);
            $(".modal-body #employee_id").val(data.id);
            $(".modal-body #id").val(data.id);
            $(this).off('shown.bs.modal');
        });


        $('#modal_salary_increment').on('shown.bs.modal', function(e){
            $(".modal-body #modal_salary_edit").text(data.username);
            $(".modal-body #employee_id").val(data.id);
            $(".modal-body #id").val(data.id);

            $(this).off('shown.bs.modal');
        });

    });
</script>
@endsection

resources/views/payslips/show.blade.php
<div id="modal_payroll_show" class="modal fade in" tabindex="-1" role="dialog" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <p class="text-muted">PAYROLL CATEGORY</p>
                <h3><span id="modal_payroll_name"></span></h3>
                <hr>
                <p class="text-muted">PAYROLL OPERAND</p>
                <H3><span id="modal_payroll_operand"> </span></H3>
                <hr>

            </div>
        </div>
    </div>
</div>